title: Code Bee
email: bhuvana.cr@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about my learnings and experiences with various web / mobile development experiements using Angular, Firebase, Ionic, Chatbots powered by different AI providers and Alexa Skill Kit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thecodebee.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: BhuvanaRajamani
github_username:  bhuvanarajamani

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5

# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - yarn.lock
  - .sass-cache
  - README.md
  - .gitignore

sass:
  sass_dir: _sass
  style: compressed
