title: Code Bee
email: dev@thecodebee.com
description: > # this means to ignore newlines until "baseurl:"
  Blog about my learnings and experiences with various web / mobile development experiements using Angular, Firebase, Ionic, Chatbots powered by different AI providers and Alexa Skill Kit.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://thecodebee.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: codebeeatwork
github_username:  thecodebee
copyright_name: Code Bee
repository: thecodebee/thecodebee.github.io

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-91428525-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title
paginate: 5

# theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - gulpfile.js
  - node_modules
  - yarn.lock
  - .sass-cache
  - README.md
  - .gitignore
  - _assets

sass:
  sass_dir: _sass
  style: compressed
